import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/main.scss";

import AuthProvider from "./_components/providers/AuthProvider";
import { AppProvider } from "./_components/providers/AppProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
            <AppProvider>{children}</AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
